In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import PowerTransformer
from sklearn.metrics import accuracy_score
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import GridSearchCV

In [13]:
df_train = pd.read_csv(r'D:\ML\Finding_defect\Files\train.csv')
df_test = pd.read_csv(r'D:\ML\Finding_defect\Files\test.csv')

In [14]:

df_train.drop(df_train.columns[0:3], axis =1, inplace= True)
df_train

ns  nd  nf  entrophy  la  ld    lt  fix  ndev         age  nuc  exp  \
0        1   1   2   0.32016  28   1  3377    1     1    0.183495    2    1   
1        1   1   1   0.00000   1   1   341    0     1    0.003368    2    1   
2        1   1   1   0.00000   1   1  3070    0     2    0.007373    3    0   
3        1   1   1   0.00000   4   2   341    0     2    0.905683    3    1   
4        1   1   1   0.00000   1   1  3063    1     2    0.997164    4    2   
...     ..  ..  ..       ...  ..  ..   ...  ...   ...         ...  ...  ...   
114374   1   1   1   0.00000  11  11   844    0     9  203.858808   88    0   
114375   1   1   1   0.00000   4   2   598    0    15   64.740243   42    1   
114376   1   1   1   0.00000   2   2  1036    0     6   29.489375   34  349   
114377   1   1   1   0.00000   2   2  1044    0    10   40.960174   22  350   
114378   1   1   1   0.00000   2   3  1230    1     1   15.584363    4   32   

            rexp  sexp  bug  
0       1.000000     2    0  
1       0.996643     2    0  
2       0.000000     1    0  
3       1.000000     2    1  
4       1.500710     2    0  
...          ...   ...  ...  
114374  0.000000     1    0  
114375  1.000000     1    0  
114376  4.600444    61    0  
114377  5.600444    61    0  
114378  1.581379     6    0  

[114379 rows x 15 columns]

In [15]:
df_test.drop(df_test.columns[0:3], axis =1, inplace= True)
df_test

ns  nd  nf  entrophy  la  ld    lt  fix  ndev         age   nuc   exp  \
0       1   1   1  0.000000   1   1  5821    0    32   18.932535   584     5   
1       1   1   1  0.000000   1   1   537    1     6   26.133553    33  6327   
2       1   1   2  0.454451  22   8  9003    0    50   14.708356  1034  6329   
3       1   1   1  0.000000   2   2   803    1     3  622.676447     5     0   
4       1   1   2  0.526034   9   8  6933    0    67   32.442176   694     2   
...    ..  ..  ..       ...  ..  ..   ...  ...   ...         ...   ...   ...   
30519   1   1   1  0.000000   4   4   533    0     6   41.020220    26    22   
30520   1   1   1  0.000000  25  23   361    0     4   11.307569     5    23   
30521   1   1   1  0.000000  17   0   793    0     4   12.201933    31    42   
30522   1   1   1  0.000000   2   0   810    0     4   10.728600    32    43   
30523   1   1   1  0.000000   5   0   812    1     4   10.718947    33    44   

            rexp  sexp  bug  
0       1.001763     3    0  
1      10.526771   100    0  
2      12.496427   100    0  
3       0.000000     1    0  
4       2.000000     3    0  
...          ...   ...  ...  
30519   1.919206     9    0  
30520   2.919206    10    0  
30521   1.791679     3    0  
30522   2.791679     3    0  
30523   3.791679     3    0  

[30524 rows x 15 columns]

In [16]:
df_train.describe()

ns             nd             nf       entrophy  \
count  114379.000000  114379.000000  114379.000000  114379.000000   
mean        1.092779       1.380437       2.281494       0.466353   
std         0.436587       2.744294      10.997604       3.606354   
min         1.000000       1.000000       1.000000       0.000000   
25%         1.000000       1.000000       1.000000       0.000000   
50%         1.000000       1.000000       1.000000       0.000000   
75%         1.000000       1.000000       2.000000       0.405224   
max        17.000000     132.000000     870.000000     294.165830   

                  la              ld              lt            fix  \
count  114379.000000   114379.000000   114379.000000  114379.000000   
mean       72.340622      106.326572     3176.104014       0.281162   
std      1629.416882     5006.429345    11457.141210       0.449568   
min         0.000000        0.000000        1.000000       0.000000   
25%         2.000000        1.000000      668.000000       0.000000   
50%         6.000000        3.000000     1529.000000       0.000000   
75%        25.000000       13.000000     3335.000000       1.000000   
max    255240.000000  1000000.000000  1000000.000000       1.000000   

                ndev            age            nuc            exp  \
count  114379.000000  114379.000000  114379.000000  114379.000000   
mean       16.102300      43.656656     258.114086    1764.632546   
std        17.805401     144.615691    1105.516569    2257.858844   
min         1.000000       0.000000       1.000000       0.000000   
25%         4.000000       0.595379      27.000000     163.000000   
50%        10.000000       5.266875      88.000000     821.000000   
75%        22.000000      30.088339     251.000000    2512.000000   
max       403.000000    5850.809086   75913.000000   12189.000000   

                rexp           sexp            bug  
count  114379.000000  114379.000000  114379.000000  
mean       24.890147     105.757412       0.474388  
std        41.199174     149.441897       0.499346  
min         0.000000       1.000000       0.000000  
25%         5.399529      15.000000       0.000000  
50%        13.414323      49.000000       0.000000  
75%        28.796882     132.000000       1.000000  
max      1504.158111    1708.000000       1.000000

In [67]:
df_test.describe()

ns            nd            nf      entrophy             la  \
count  30524.000000  30524.000000  30524.000000  30524.000000   30524.000000   
mean       1.141888      1.487780      2.456886      0.524585     107.539215   
std        0.546213      2.835799     11.524380      3.738493    3240.846949   
min        1.000000      1.000000      1.000000      0.000000       0.000000   
25%        1.000000      1.000000      1.000000      0.000000       2.000000   
50%        1.000000      1.000000      1.000000      0.000000       7.000000   
75%        1.000000      1.000000      2.000000      0.500000      24.000000   
max       11.000000    105.000000    525.000000    170.169678  324897.000000   

                  ld             lt           fix          ndev           age  \
count   30524.000000   30524.000000  30524.000000  30524.000000  30524.000000   
mean      108.253473    4530.027781      0.286332     31.530337     71.232591   
std      3160.026535   16530.026238      0.452054     36.876733    190.962629   
min         0.000000       1.000000      0.000000      1.000000      0.000000   
25%         1.000000     854.000000      0.000000      8.000000      2.001704   
50%         4.000000    1992.500000      0.000000     18.000000     13.734436   
75%        15.000000    4630.250000      1.000000     45.000000     59.616649   
max    317342.000000  764428.000000      1.000000    713.000000   6032.320428   

                nuc           exp          rexp          sexp           bug  
count  30524.000000  30524.000000  30524.000000  30524.000000  30524.000000  
mean     529.968877   4519.935592     25.565555    185.694568      0.362600  
std     2018.932895   5465.343316     38.984538    229.479778      0.480759  
min        1.000000      0.000000      0.000000      1.000000      0.000000  
25%       56.000000    160.000000      4.097131     21.000000      0.000000  
50%      201.000000   1768.500000     16.044882     73.000000      0.000000  
75%      521.000000   7333.000000     35.966436    274.000000      1.000000  
max    84381.000000  19097.000000   1477.258842   1764.000000      1.000000

In [68]:
y_train = df_train['bug']
y_test = df_test['bug']
y_test

0        0
1        0
2        0
3        0
4        0
        ..
30519    0
30520    0
30521    0
30522    0
30523    0
Name: bug, Length: 30524, dtype: int64

In [69]:
df_train.drop(['bug'], axis=1, inplace= True)
df_test.drop(['bug'], axis=1, inplace= True)
X_train = df_train
X_test = df_test
X_test

ns  nd  nf  entrophy  la  ld    lt  fix  ndev         age   nuc   exp  \
0       1   1   1  0.000000   1   1  5821    0    32   18.932535   584     5   
1       1   1   1  0.000000   1   1   537    1     6   26.133553    33  6327   
2       1   1   2  0.454451  22   8  9003    0    50   14.708356  1034  6329   
3       1   1   1  0.000000   2   2   803    1     3  622.676447     5     0   
4       1   1   2  0.526034   9   8  6933    0    67   32.442176   694     2   
...    ..  ..  ..       ...  ..  ..   ...  ...   ...         ...   ...   ...   
30519   1   1   1  0.000000   4   4   533    0     6   41.020220    26    22   
30520   1   1   1  0.000000  25  23   361    0     4   11.307569     5    23   
30521   1   1   1  0.000000  17   0   793    0     4   12.201933    31    42   
30522   1   1   1  0.000000   2   0   810    0     4   10.728600    32    43   
30523   1   1   1  0.000000   5   0   812    1     4   10.718947    33    44   

            rexp  sexp  
0       1.001763     3  
1      10.526771   100  
2      12.496427   100  
3       0.000000     1  
4       2.000000     3  
...          ...   ...  
30519   1.919206     9  
30520   2.919206    10  
30521   1.791679     3  
30522   2.791679     3  
30523   3.791679     3  

[30524 rows x 14 columns]

In [48]:
pt = PowerTransformer()
pX_train = pt.fit_transform(X_train)
pX_test = pt.transform(X_test)

In [49]:
rs = RobustScaler()
rX_train = rs.fit_transform(pX_train)
rX_test = rs.transform(pX_test)

In [50]:
sc = StandardScaler()
zX_train = sc.fit_transform(rX_train)
zX_test = sc.transform(rX_test)

In [51]:
zX_train = pd.DataFrame(zX_train)
zX_train.describe()

0             1             2             3             4   \
count  1.143790e+05  1.143790e+05  1.143790e+05  1.143790e+05  1.143790e+05   
mean  -9.939485e-18  3.031543e-17 -5.069137e-17 -1.148011e-16  3.031543e-17   
std    1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00   
min   -2.668805e-01 -4.094889e-01 -6.070269e-01 -6.063925e-01 -1.949729e+00   
25%   -2.668805e-01 -4.094889e-01 -6.070269e-01 -6.063925e-01 -7.957304e-01   
50%   -2.668805e-01 -4.094889e-01 -6.070269e-01 -6.063925e-01 -8.261927e-02   
75%   -2.668805e-01 -4.094889e-01  1.334039e+00  1.291042e+00  7.838449e-01   
max    3.747012e+00  2.470009e+00  1.981652e+00  1.955417e+00  2.973674e+00   

                 5             6             7             8             9   \
count  1.143790e+05  1.143790e+05  1.143790e+05  1.143790e+05  1.143790e+05   
mean   4.969743e-17 -2.783056e-17 -3.180635e-17 -1.590318e-17 -5.963691e-18   
std    1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00  1.000004e+00   
min   -1.522226e+00 -4.862487e+00 -6.254067e-01 -1.779110e+00 -1.346445e+00   
25%   -7.237995e-01 -6.477392e-01 -6.254067e-01 -8.139984e-01 -9.600948e-01   
50%   -8.010438e-02  2.405982e-02 -6.254067e-01  8.641535e-03  1.414858e-04   
75%    7.834767e-01  6.749494e-01  1.598960e+00  7.717221e-01  8.595364e-01   
max    2.541460e+00  6.011093e+00  1.598960e+00  3.678010e+00  2.422798e+00   

                 10             11            12            13  
count  1.143790e+05  114379.000000  1.143790e+05  1.143790e+05  
mean   1.590318e-17       0.000000 -3.975794e-17 -3.180635e-17  
std    1.000004e+00       1.000004  1.000004e+00  1.000004e+00  
min   -2.219123e+00      -2.012489 -2.225995e+00 -1.894829e+00  
25%   -6.920106e-01      -0.740795 -6.829431e-01 -7.025254e-01  
50%    2.863216e-02       0.043791  1.983580e-02  4.146914e-02  
75%    7.057679e-01       0.768667  6.631598e-01  7.376055e-01  
max    4.953533e+00       2.135616  4.393590e+00  2.837998e+00

In [70]:
model = LogisticRegression(solver = 'saga', class_weight='balanced', random_state=20, max_iter=10000, penalty= 'l1', C = 1)
model.fit(zX_train, y_train)

LogisticRegression(C=1, class_weight='balanced', max_iter=10000, penalty='l1',
                   random_state=20, solver='saga')

In [73]:
y_predict = model.predict(zX_test)
y_predict

array([0, 0, 1, ..., 1, 0, 0])

In [58]:
#y_proba = model.predict_proba(zX_test)[:,1]
#threshold = 0.3
#y_predict = (y_proba >= threshold).astype(int)
#y_predict

array([0, 0, 1, ..., 1, 0, 1])

In [71]:
sklearn.metrics.accuracy_score(y_test, y_predict)

0.540885860306644

In [72]:
sklearn.metrics.confusion_matrix(y_test, y_predict)

array([[ 6693, 12763],
       [ 1251,  9817]])

In [26]:
sklearn.metrics.precision_score(y_test, y_predict)

np.float64(0.5672521803218278)

In [61]:
sklearn.metrics.recall_score(y_test, y_predict)

np.float64(0.8869714492229852)

In [28]:
sklearn.metrics.f1_score(y_test, y_predict)

np.float64(0.48081628403352594)

In [55]:
sklearn.metrics.roc_auc_score(y_test, y_predict)

np.float64(0.6180818200852861)